/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Text;
export const ApplicationResult = IDL.Variant({
  'failure' : IDL.Record({
    'removedFromQueue' : IDL.Bool,
    'message' : IDL.Text,
  }),
  'hint' : IDL.Null,
  'success' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ModeratorId = IDL.Text;
export const Moderator = IDL.Record({
  'id' : ModeratorId,
  'status' : IDL.Variant({ 'active' : IDL.Null, 'banned' : IDL.Null }),
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'banReason' : IDL.Text,
});
export const User = IDL.Record({
  'id' : UserId,
  'status' : IDL.Variant({
    'active' : IDL.Null,
    'banned' : IDL.Null,
    'warned' : IDL.Null,
  }),
  'warningCount' : IDL.Nat,
  'username' : IDL.Text,
  'adminAppealResponse' : IDL.Opt(IDL.Text),
  'banReason' : IDL.Text,
  'banAppealStatus' : IDL.Variant({
    'pending' : IDL.Null,
    'none' : IDL.Null,
    'reviewed' : IDL.Null,
  }),
  'isBanned' : IDL.Bool,
  'banAppealText' : IDL.Text,
  'maxWarnings' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'name' : IDL.Text,
});
export const ApplicationId = IDL.Text;
export const ModeratorApplication = IDL.Record({
  'id' : ApplicationId,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'denied' : IDL.Null,
    'approved' : IDL.Null,
  }),
  'applicantPrincipal' : IDL.Principal,
  'wasWarned' : IDL.Bool,
  'timestamp' : IDL.Int,
  'applicantUserId' : IDL.Opt(UserId),
  'adminResponse' : IDL.Opt(IDL.Text),
});
export const ReportId = IDL.Text;
export const ModeratorReport = IDL.Record({
  'id' : ReportId,
  'status' : IDL.Variant({ 'resolved' : IDL.Null, 'pending' : IDL.Null }),
  'reportedModeratorId' : ModeratorId,
  'timestamp' : IDL.Int,
  'reportedByUserId' : UserId,
  'adminResponse' : IDL.Opt(IDL.Text),
  'reason' : IDL.Text,
});
export const WarningId = IDL.Text;
export const Warning = IDL.Record({
  'id' : WarningId,
  'issuedByModeratorId' : ModeratorId,
  'timestamp' : IDL.Int,
  'reason' : IDL.Text,
  'targetUserId' : UserId,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addModerator' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'addUser' : IDL.Func([UserId, IDL.Text], [], []),
  'applyForModerator' : IDL.Func(
      [IDL.Text, IDL.Opt(UserId)],
      [ApplicationResult],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banUser' : IDL.Func([UserId, IDL.Text], [], []),
  'getAllModerators' : IDL.Func([], [IDL.Vec(Moderator)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getModeratorApplications' : IDL.Func(
      [],
      [IDL.Vec(ModeratorApplication)],
      ['query'],
    ),
  'getModeratorReports' : IDL.Func([], [IDL.Vec(ModeratorReport)], ['query']),
  'getMyAppealStatus' : IDL.Func([UserId], [IDL.Text], ['query']),
  'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserWarnings' : IDL.Func([UserId], [IDL.Vec(Warning)], ['query']),
  'instantBanUser' : IDL.Func([UserId], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'issueWarning' : IDL.Func([UserId, IDL.Text], [], []),
  'recordSearchAttempt' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'reportModerator' : IDL.Func([ModeratorId, IDL.Text], [], []),
  'resolveModeratorReport' : IDL.Func([ReportId, IDL.Bool], [], []),
  'respondToAppeal' : IDL.Func([IDL.Principal, IDL.Text], [Result], []),
  'respondToModeratorApplication' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
  'respondToModeratorReport' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
  'reviewAppeal' : IDL.Func(
      [UserId, IDL.Variant({ 'deny' : IDL.Null, 'approve' : IDL.Null })],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAppeal' : IDL.Func([UserId, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Text;
  const ApplicationResult = IDL.Variant({
    'failure' : IDL.Record({
      'removedFromQueue' : IDL.Bool,
      'message' : IDL.Text,
    }),
    'hint' : IDL.Null,
    'success' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ModeratorId = IDL.Text;
  const Moderator = IDL.Record({
    'id' : ModeratorId,
    'status' : IDL.Variant({ 'active' : IDL.Null, 'banned' : IDL.Null }),
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'banReason' : IDL.Text,
  });
  const User = IDL.Record({
    'id' : UserId,
    'status' : IDL.Variant({
      'active' : IDL.Null,
      'banned' : IDL.Null,
      'warned' : IDL.Null,
    }),
    'warningCount' : IDL.Nat,
    'username' : IDL.Text,
    'adminAppealResponse' : IDL.Opt(IDL.Text),
    'banReason' : IDL.Text,
    'banAppealStatus' : IDL.Variant({
      'pending' : IDL.Null,
      'none' : IDL.Null,
      'reviewed' : IDL.Null,
    }),
    'isBanned' : IDL.Bool,
    'banAppealText' : IDL.Text,
    'maxWarnings' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'username' : IDL.Text, 'name' : IDL.Text });
  const ApplicationId = IDL.Text;
  const ModeratorApplication = IDL.Record({
    'id' : ApplicationId,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'denied' : IDL.Null,
      'approved' : IDL.Null,
    }),
    'applicantPrincipal' : IDL.Principal,
    'wasWarned' : IDL.Bool,
    'timestamp' : IDL.Int,
    'applicantUserId' : IDL.Opt(UserId),
    'adminResponse' : IDL.Opt(IDL.Text),
  });
  const ReportId = IDL.Text;
  const ModeratorReport = IDL.Record({
    'id' : ReportId,
    'status' : IDL.Variant({ 'resolved' : IDL.Null, 'pending' : IDL.Null }),
    'reportedModeratorId' : ModeratorId,
    'timestamp' : IDL.Int,
    'reportedByUserId' : UserId,
    'adminResponse' : IDL.Opt(IDL.Text),
    'reason' : IDL.Text,
  });
  const WarningId = IDL.Text;
  const Warning = IDL.Record({
    'id' : WarningId,
    'issuedByModeratorId' : ModeratorId,
    'timestamp' : IDL.Int,
    'reason' : IDL.Text,
    'targetUserId' : UserId,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addModerator' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'addUser' : IDL.Func([UserId, IDL.Text], [], []),
    'applyForModerator' : IDL.Func(
        [IDL.Text, IDL.Opt(UserId)],
        [ApplicationResult],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banUser' : IDL.Func([UserId, IDL.Text], [], []),
    'getAllModerators' : IDL.Func([], [IDL.Vec(Moderator)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getModeratorApplications' : IDL.Func(
        [],
        [IDL.Vec(ModeratorApplication)],
        ['query'],
      ),
    'getModeratorReports' : IDL.Func([], [IDL.Vec(ModeratorReport)], ['query']),
    'getMyAppealStatus' : IDL.Func([UserId], [IDL.Text], ['query']),
    'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserWarnings' : IDL.Func([UserId], [IDL.Vec(Warning)], ['query']),
    'instantBanUser' : IDL.Func([UserId], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'issueWarning' : IDL.Func([UserId, IDL.Text], [], []),
    'recordSearchAttempt' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'reportModerator' : IDL.Func([ModeratorId, IDL.Text], [], []),
    'resolveModeratorReport' : IDL.Func([ReportId, IDL.Bool], [], []),
    'respondToAppeal' : IDL.Func([IDL.Principal, IDL.Text], [Result], []),
    'respondToModeratorApplication' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [Result],
        [],
      ),
    'respondToModeratorReport' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
    'reviewAppeal' : IDL.Func(
        [UserId, IDL.Variant({ 'deny' : IDL.Null, 'approve' : IDL.Null })],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAppeal' : IDL.Func([UserId, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };