/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApplicationId = string;
export type ApplicationResult = {
    'failure' : { 'removedFromQueue' : boolean, 'message' : string }
  } |
  { 'hint' : null } |
  { 'success' : null };
export interface Moderator {
  'id' : ModeratorId,
  'status' : { 'active' : null } |
    { 'banned' : null },
  'principal' : Principal,
  'name' : string,
  'banReason' : string,
}
export interface ModeratorApplication {
  'id' : ApplicationId,
  'status' : { 'pending' : null } |
    { 'denied' : null } |
    { 'approved' : null },
  'applicantPrincipal' : Principal,
  'wasWarned' : boolean,
  'timestamp' : bigint,
  'applicantUserId' : [] | [UserId],
  'adminResponse' : [] | [string],
}
export type ModeratorId = string;
export interface ModeratorReport {
  'id' : ReportId,
  'status' : { 'resolved' : null } |
    { 'pending' : null },
  'reportedModeratorId' : ModeratorId,
  'timestamp' : bigint,
  'reportedByUserId' : UserId,
  'adminResponse' : [] | [string],
  'reason' : string,
}
export type ReportId = string;
export type Result = { 'ok' : null } |
  { 'err' : string };
export interface User {
  'id' : UserId,
  'status' : { 'active' : null } |
    { 'banned' : null } |
    { 'warned' : null },
  'warningCount' : bigint,
  'username' : string,
  'adminAppealResponse' : [] | [string],
  'banReason' : string,
  'banAppealStatus' : { 'pending' : null } |
    { 'none' : null } |
    { 'reviewed' : null },
  'isBanned' : boolean,
  'banAppealText' : string,
  'maxWarnings' : bigint,
}
export type UserId = string;
export interface UserProfile { 'username' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Warning {
  'id' : WarningId,
  'issuedByModeratorId' : ModeratorId,
  'timestamp' : bigint,
  'reason' : string,
  'targetUserId' : UserId,
}
export type WarningId = string;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addModerator' : ActorMethod<[Principal, string], undefined>,
  'addUser' : ActorMethod<[UserId, string], undefined>,
  'applyForModerator' : ActorMethod<[string, [] | [UserId]], ApplicationResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banUser' : ActorMethod<[UserId, string], undefined>,
  'getAllModerators' : ActorMethod<[], Array<Moderator>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getModeratorApplications' : ActorMethod<[], Array<ModeratorApplication>>,
  'getModeratorReports' : ActorMethod<[], Array<ModeratorReport>>,
  'getMyAppealStatus' : ActorMethod<[UserId], string>,
  'getUser' : ActorMethod<[UserId], [] | [User]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserWarnings' : ActorMethod<[UserId], Array<Warning>>,
  'instantBanUser' : ActorMethod<[UserId], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'issueWarning' : ActorMethod<[UserId, string], undefined>,
  'recordSearchAttempt' : ActorMethod<[Principal], boolean>,
  'reportModerator' : ActorMethod<[ModeratorId, string], undefined>,
  'resolveModeratorReport' : ActorMethod<[ReportId, boolean], undefined>,
  'respondToAppeal' : ActorMethod<[Principal, string], Result>,
  'respondToModeratorApplication' : ActorMethod<[bigint, string], Result>,
  'respondToModeratorReport' : ActorMethod<[bigint, string], Result>,
  'reviewAppeal' : ActorMethod<
    [UserId, { 'deny' : null } | { 'approve' : null }],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAppeal' : ActorMethod<[UserId, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];